FROM typesense/docsearch-scraper-base
LABEL maintainer="contact@typesense.org"

WORKDIR /home/seleuser
USER seleuser

# Copy DocSearch files
COPY . .
RUN touch .env
ENTRYPOINT ["pipenv", "run", "./docsearch", "test", "no_browser"]
